// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// 
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using Oanda.Rest;
using Oanda.Rest.Models;

namespace Oanda.Rest
{
    public static partial class OandaRestAPIExtensions
    {
        /// <param name='operations'>
        /// Reference to the Oanda.Rest.IOandaRestAPI.
        /// </param>
        public static GetAccountListOKResponse GetAccountList(this IOandaRestAPI operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IOandaRestAPI)s).GetAccountListAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Oanda.Rest.IOandaRestAPI.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<GetAccountListOKResponse> GetAccountListAsync(this IOandaRestAPI operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Oanda.Rest.Models.GetAccountListOKResponse> result = await operations.GetAccountListWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
