// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Oanda.Rest.Models
{
    public partial class Account
    {
        private string _accountCurrency;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AccountCurrency
        {
            get { return this._accountCurrency; }
            set { this._accountCurrency = value; }
        }
        
        private int? _accountId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? AccountId
        {
            get { return this._accountId; }
            set { this._accountId = value; }
        }
        
        private string _accountName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AccountName
        {
            get { return this._accountName; }
            set { this._accountName = value; }
        }
        
        private double? _marginRate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? MarginRate
        {
            get { return this._marginRate; }
            set { this._marginRate = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Account class.
        /// </summary>
        public Account()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken accountCurrencyValue = inputObject["accountCurrency"];
                if (accountCurrencyValue != null && accountCurrencyValue.Type != JTokenType.Null)
                {
                    this.AccountCurrency = ((string)accountCurrencyValue);
                }
                JToken accountIdValue = inputObject["accountId"];
                if (accountIdValue != null && accountIdValue.Type != JTokenType.Null)
                {
                    this.AccountId = ((int)accountIdValue);
                }
                JToken accountNameValue = inputObject["accountName"];
                if (accountNameValue != null && accountNameValue.Type != JTokenType.Null)
                {
                    this.AccountName = ((string)accountNameValue);
                }
                JToken marginRateValue = inputObject["marginRate"];
                if (marginRateValue != null && marginRateValue.Type != JTokenType.Null)
                {
                    this.MarginRate = ((double)marginRateValue);
                }
            }
        }
    }
}
