// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Oanda.Rest.Models
{
    public partial class Candle
    {
        private string _time;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Time
        {
            get { return this._time; }
            set { this._time = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Candle class.
        /// </summary>
        public Candle()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken timeValue = inputObject["time"];
                if (timeValue != null && timeValue.Type != JTokenType.Null)
                {
                    this.Time = ((string)timeValue);
                }
            }
        }
    }
}
