// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Oanda.Rest.Models
{
    public partial class CreateAccountOKResponse
    {
        private string _accountId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AccountId
        {
            get { return this._accountId; }
            set { this._accountId = value; }
        }
        
        private string _password;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Password
        {
            get { return this._password; }
            set { this._password = value; }
        }
        
        private string _username;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Username
        {
            get { return this._username; }
            set { this._username = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CreateAccountOKResponse class.
        /// </summary>
        public CreateAccountOKResponse()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken accountIdValue = inputObject["accountId"];
                if (accountIdValue != null && accountIdValue.Type != JTokenType.Null)
                {
                    this.AccountId = ((string)accountIdValue);
                }
                JToken passwordValue = inputObject["password"];
                if (passwordValue != null && passwordValue.Type != JTokenType.Null)
                {
                    this.Password = ((string)passwordValue);
                }
                JToken usernameValue = inputObject["username"];
                if (usernameValue != null && usernameValue.Type != JTokenType.Null)
                {
                    this.Username = ((string)usernameValue);
                }
            }
        }
    }
}
