// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// 
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace Oanda.Rest.Models
{
    public partial class Error
    {
        private int? _code;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Code
        {
            get { return this._code; }
            set { this._code = value; }
        }
        
        private string _message;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Message
        {
            get { return this._message; }
            set { this._message = value; }
        }
        
        private string _moreInfo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string MoreInfo
        {
            get { return this._moreInfo; }
            set { this._moreInfo = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Error class.
        /// </summary>
        public Error()
        {
        }
    }
}
