// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Oanda.Rest.Models
{
    public partial class Error
    {
        private int? _code;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Code
        {
            get { return this._code; }
            set { this._code = value; }
        }
        
        private string _message;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Message
        {
            get { return this._message; }
            set { this._message = value; }
        }
        
        private string _moreInfo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string MoreInfo
        {
            get { return this._moreInfo; }
            set { this._moreInfo = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Error class.
        /// </summary>
        public Error()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken codeValue = inputObject["code"];
                if (codeValue != null && codeValue.Type != JTokenType.Null)
                {
                    this.Code = ((int)codeValue);
                }
                JToken messageValue = inputObject["message"];
                if (messageValue != null && messageValue.Type != JTokenType.Null)
                {
                    this.Message = ((string)messageValue);
                }
                JToken moreInfoValue = inputObject["moreInfo"];
                if (moreInfoValue != null && moreInfoValue.Type != JTokenType.Null)
                {
                    this.MoreInfo = ((string)moreInfoValue);
                }
            }
        }
    }
}
