// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using Oanda.Rest.Models;

namespace Oanda.Rest.Models
{
    public partial class GetPricesOKResponse : IEnumerable<Price>
    {
        private IList<Price> _prices;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<Price> Prices
        {
            get { return this._prices; }
            set { this._prices = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the GetPricesOKResponse class.
        /// </summary>
        public GetPricesOKResponse()
        {
            this.Prices = new LazyList<Price>();
        }
        
        /// <summary>
        /// Gets the sequence of prices.
        /// </summary>
        public IEnumerator<Price> GetEnumerator()
        {
            return this.Prices.GetEnumerator();
        }
        
        /// <summary>
        /// Gets the sequence of prices.
        /// </summary>
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken pricesSequence = ((JToken)inputObject["prices"]);
                if (pricesSequence != null && pricesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken pricesValue in ((JArray)pricesSequence))
                    {
                        Price price = new Price();
                        price.DeserializeJson(pricesValue);
                        this.Prices.Add(price);
                    }
                }
            }
        }
    }
}
